### ISSUE TITLE
只是来打个招呼喵~

### ISSUE THREAD

**Issue by 3c0tr** [WisenextTime/TheMage#4]
在看tomlyn仓库时意外点进了你的仓库，然后惊奇地发现是一个godot项目，比较好奇是什么类型的游戏哩.

**Comment by WisenextTime** [comment]
> 在看tomlyn仓库时意外点进了你的仓库，然后惊奇地发现是一个godot项目，比较好奇是什么类型的游戏哩.

是一个ARPG游戏，不过我比较好奇你是如何在看tomlyn仓库时找到我的仓库的

**Comment by 3c0tr** [comment]
就是这里！![image](https://github.com/user-attachments/assets/e216a675-612b-46a6-8397-65f3c6edf63a)

**Comment by WisenextTime** [comment]
> 就是这里！![image](https://github.com/user-attachments/assets/e216a675-612b-46a6-8397-65f3c6edf63a)
> 
原来如此，不过贴图那边暂时出了点问题，所以说这个项目暂时停滞了，最近我在做一个rts

**Comment by KirisameY** [comment]
www以意外的形式被发现了呢

**Comment by 3c0tr** [comment]
> 原来如此，不过贴图那边暂时出了点问题，所以说这个项目暂时停滞了，最近我在做一个rts

天哪，现在还有人愿意做rts......应该也是rts真爱了（我也是呢）......
